{ name: '', command: { } },
var allConfig = {
Quit {skip_confirmation: bool,},
PowerOffMonitors {},
PowerOnMonitors {},
Spawn {command: Vec<String>,},
SpawnSh {command: String,},
DoScreenTransition {delay_ms: Option<u16>,},
Screenshot {show_pointer: bool,},
ScreenshotScreen {write_to_disk: bool,show_pointer: bool,},
ScreenshotWindow {id: Option<u64>,write_to_disk: bool,},
ToggleKeyboardShortcutsInhibit {},
CloseWindow {id: Option<u64>,},
FullscreenWindow {id: Option<u64>,},
ToggleWindowedFullscreen {id: Option<u64>,},
FocusWindow {id: u64,},
FocusWindowInColumn {index: u8,},
FocusWindowPrevious {},
FocusColumnLeft {},
FocusColumnRight {},
FocusColumnFirst {},
FocusColumnLast {},
FocusColumnRightOrFirst {},
FocusColumnLeftOrLast {},
FocusColumn {index: usize,},
FocusWindowOrMonitorUp {},
FocusWindowOrMonitorDown {},
FocusColumnOrMonitorLeft {},
FocusColumnOrMonitorRight {},
FocusWindowDown {},
FocusWindowUp {},
FocusWindowDownOrColumnLeft {},
FocusWindowDownOrColumnRight {},
FocusWindowUpOrColumnLeft {},
FocusWindowUpOrColumnRight {},
FocusWindowOrWorkspaceDown {},
FocusWindowOrWorkspaceUp {},
FocusWindowTop {},
FocusWindowBottom {},
FocusWindowDownOrTop {},
FocusWindowUpOrBottom {},
MoveColumnLeft {},
MoveColumnRight {},
MoveColumnToFirst {},
MoveColumnToLast {},
MoveColumnLeftOrToMonitorLeft {},
MoveColumnRightOrToMonitorRight {},
MoveColumnToIndex {index: usize,},
MoveWindowDown {},
MoveWindowUp {},
MoveWindowDownOrToWorkspaceDown {},
MoveWindowUpOrToWorkspaceUp {},
ConsumeOrExpelWindowLeft {id: Option<u64>,},
ConsumeOrExpelWindowRight {id: Option<u64>,},
ConsumeWindowIntoColumn {},
ExpelWindowFromColumn {},
SwapWindowRight {},
SwapWindowLeft {},
ToggleColumnTabbedDisplay {},
SetColumnDisplay {display: ColumnDisplay,},
CenterColumn {},
CenterWindow {id: Option<u64>,},
CenterVisibleColumns {},
FocusWorkspaceDown {},
FocusWorkspaceUp {},
FocusWorkspace {reference: WorkspaceReferenceArg,},
FocusWorkspacePrevious {},
MoveWindowToWorkspaceDown {focus: bool,},
MoveWindowToWorkspaceUp {focus: bool,},
MoveWindowToWorkspace {window_id: Option<u64>,reference: WorkspaceReferenceArg,focus: bool,},
MoveColumnToWorkspaceDown {focus: bool,},
MoveColumnToWorkspaceUp {focus: bool,},
MoveColumnToWorkspace {reference: WorkspaceReferenceArg,focus: bool,},
MoveWorkspaceDown {},
MoveWorkspaceUp {},
MoveWorkspaceToIndex {index: usize,reference: Option<WorkspaceReferenceArg>,},
SetWorkspaceName {name: String,workspace: Option<WorkspaceReferenceArg>,},
UnsetWorkspaceName {reference: Option<WorkspaceReferenceArg>,},
FocusMonitorLeft {},
FocusMonitorRight {},
FocusMonitorDown {},
FocusMonitorUp {},
FocusMonitorPrevious {},
FocusMonitorNext {},
FocusMonitor {output: String,},
MoveWindowToMonitorLeft {},
MoveWindowToMonitorRight {},
MoveWindowToMonitorDown {},
MoveWindowToMonitorUp {},
MoveWindowToMonitorPrevious {},
MoveWindowToMonitorNext {},
MoveWindowToMonitor {id: Option<u64>,output: String,},
MoveColumnToMonitorLeft {},
MoveColumnToMonitorRight {},
MoveColumnToMonitorDown {},
MoveColumnToMonitorUp {},
MoveColumnToMonitorPrevious {},
MoveColumnToMonitorNext {},
MoveColumnToMonitor {output: String,},
SetWindowWidth {id: Option<u64>,change: SizeChange,},
SetWindowHeight {id: Option<u64>,change: SizeChange,},
ResetWindowHeight {id: Option<u64>,},
SwitchPresetColumnWidth {},
SwitchPresetColumnWidthBack {},
SwitchPresetWindowWidth {id: Option<u64>,},
SwitchPresetWindowWidthBack {id: Option<u64>,},
SwitchPresetWindowHeight {id: Option<u64>,},
SwitchPresetWindowHeightBack {id: Option<u64>,},
MaximizeColumn {},
SetColumnWidth {change: SizeChange,},
ExpandColumnToAvailableWidth {},
SwitchLayout {layout: LayoutSwitchTarget,},
ShowHotkeyOverlay {},
MoveWorkspaceToMonitorLeft {},
MoveWorkspaceToMonitorRight {},
MoveWorkspaceToMonitorDown {},
MoveWorkspaceToMonitorUp {},
MoveWorkspaceToMonitorPrevious {},
MoveWorkspaceToMonitorNext {},
MoveWorkspaceToMonitor {output: String,reference: Option<WorkspaceReferenceArg>,},
ToggleDebugTint {},
DebugToggleOpaqueRegions {},
DebugToggleDamage {},
ToggleWindowFloating {id: Option<u64>,},
MoveWindowToFloating {id: Option<u64>,},
MoveWindowToTiling {id: Option<u64>,},
FocusFloating {},
FocusTiling {},
SwitchFocusBetweenFloatingAndTiling {},
MoveFloatingWindow {id: Option<u64>,x: PositionChange,y: PositionChange,},
ToggleWindowRuleOpacity {id: Option<u64>,},
SetDynamicCastWindow {id: Option<u64>,},
SetDynamicCastMonitor {output: Option<String>,},
ClearDynamicCastTarget {},
ToggleOverview {},
OpenOverview {},
CloseOverview {},
ToggleWindowUrgent {id: u64,},
SetWindowUrgent {id: u64,},
UnsetWindowUrgent {id: u64,},
LoadConfigFile {},
}


property var groupConfig: (() => {
		return {
			// columnFocus: {
			// 	label: 'Col\nfocus',
			// 	items: [
			// 		{ name: '◀', command: 'focus-column-left' },
			// 		{ name: '▶', command: 'focus-column-right' },
			// 		{ name: '┃◀', command: 'focus-column-first' },
			// 		{ name: '▶┃', command: 'focus-column-last' },
			// 		{ name: '▶ or ┃◀', command: 'focus-column-right-or-first' },
			// 		{ name: '◀ or ▶┃', command: 'focus-column-left-or-last' },
			// 		{ name: '◀ or 🖥️', command: 'focus-column-or-monitor-left' },
			// 		{ name: '▶ or 🖥️', command: 'focus-column-or-monitor-right' },
			// 		// FocusColumn {index: usize,},
			// 	]
			// },
			// columnMove: {
			// 	label: 'Col\nmove',
			// 	items: [
			// 		{ name: '◀', command: 'move-column-left' },
			// 		{ name: '▶', command: 'move-column-right' },
			// 		{ name: '┃◀', command: 'move-column-to-first' },
			// 		{ name: '▶┃', command: 'move-column-to-last' },
			// 		{ name: '◀ Or To 🖥️ ◀', command: 'move-column-left-or-to-monitor-left' },
			// 		{ name: '▶ Or To 🖥️ ▶', command: 'move-column-right-or-to-monitor-right' },
			// 		{ name: 'To 🖥️ ◀', command: 'move-column-to-monitor-left' },
			// 		{ name: 'To 🖥️ ▶', command: 'move-column-to-monitor-right' },
			// 		{ name: 'To 🖥️ ▼', command: 'move-column-to-monitor-down' },
			// 		{ name: 'To 🖥️ ▲', command: 'move-column-to-monitor-up' },
			// 		{ name: 'To 🖥️ Prev', command: 'move-column-to-monitor-previous' },
			// 		{ name: 'To 🖥️ Next', command: 'move-column-to-monitor-next' },
			// 		{ name: 'To Ws ▼', command: 'move-column-to-workspace-down' },// MoveColumnToWorkspaceDown {focus: bool,},
			// 		{ name: 'To Ws ▲', command: 'move-column-to-workspace-up' },// MoveColumnToWorkspaceUp {focus: bool,},
			// 		// MoveColumnToIndex {index: usize,},
			// 		// MoveColumnToWorkspace {reference: WorkspaceReferenceArg,focus: bool,},
			// 		// MoveColumnToMonitor {output: String,},
			// 	]
			// },
			// windowFocus: {
			// 	label: '🪟\nfocus',
			// 	items: [
			// 		{ name: 'Prev', command: 'focus-window-previous' },
			// 		{ name: 'Or 🖥️ ▲', command: 'focus-window-or-monitor-up' },
			// 		{ name: 'Or 🖥️ ▼', command: 'focus-window-or-monitor-down' },
			// 		{ name: '▼', command: 'focus-window-down' },
			// 		{ name: '▲', command: 'focus-window-up' },
			// 		{ name: '▼ Or Col ◀', command: 'focus-window-down-or-column-left' },
			// 		{ name: '▼ Or Col ▶', command: 'focus-window-down-or-column-right' },
			// 		{ name: '▲ Or Col ◀', command: 'focus-window-up-or-column-left' },
			// 		{ name: '▲ Or Col ▶', command: 'focus-window-up-or-column-right' },
			// 		{ name: 'Or Workspace ▼', command: 'focus-window-or-workspace-down' },
			// 		{ name: 'Or Workspace ▲', command: 'focus-window-or-workspace-up' },
			// 		{ name: 'Top', command: 'focus-window-top' },
			// 		{ name: 'Bottom', command: 'focus-window-bottom' },
			// 		{ name: '▼ Or Top', command: 'focus-window-down-or-top' },
			// 		{ name: '▲ Or Bottom', command: 'focus-window-up-or-bottom' },
			// 		// FocusWindow {id: u64,},
    	// 		// FocusWindowInColumn {index: u8,},
			// 	]
			// },
			// windowMove: {
			// 	label: '🪟\nmove',
			// 	items: [
			// 		{ name: '▼', command: 'move-window-down' },
			// 		{ name: '▲', command: 'move-window-up' },
			// 		{ name: '▼ Or To Workspace ▼', command: 'move-window-down-or-to-workspace-down' },
			// 		{ name: '▲ Or To Workspace ▲', command: 'move-window-up-or-to-workspace-up' },
			// 		{ name: 'To 🖥️ ◀', command: 'move-window-to-monitor-left' },
			// 		{ name: 'To 🖥️ ▶', command: 'move-window-to-monitor-right' },
			// 		{ name: 'To 🖥️ ▼', command: 'move-window-to-monitor-down' },
			// 		{ name: 'To 🖥️ ▲', command: 'move-window-to-monitor-up' },
			// 		{ name: 'To 🖥️ Prev', command: 'move-window-to-monitor-previous' },
			// 		{ name: 'To 🖥️ Next', command: 'move-window-to-monitor-next' },
			// 		{ name: 'To Workspace ▼', command: 'move-window-to-workspace-down' },// MoveWindowToWorkspaceDown {focus: bool,},
			// 		{ name: 'To Workspace ▲', command: 'move-window-to-workspace-up' },// MoveWindowToWorkspaceUp {focus: bool,},
			// 		{ name: 'To Floating', command: 'move-window-to-floating' },// MoveWindowToFloating {id: Option<u64>,},
			// 		{ name: 'To Tiling', command: 'move-window-to-tiling' },// MoveWindowToTiling {id: Option<u64>,},
			// 		{ name: 'ConsumeOrExpel 🪟 ◀', command: 'consume-or-expel-window-left' },// ConsumeOrExpelWindowLeft {id: Option<u64>,},
			// 		{ name: 'ConsumeOrExpel 🪟 ▶', command: 'consume-or-expel-window-right' },// ConsumeOrExpelWindowRight {id: Option<u64>,},
			// 			// MoveWindowToWorkspace {window_id: Option<u64>,reference: WorkspaceReferenceArg,focus: bool,},
			// 			// MoveWindowToMonitor {id: Option<u64>,output: String,},
			// 	]
			// },
			// workspaceFocus: {
			// 	label: 'Workspace\nfocus',
			// 	items: [
			// 		{ name: '▼', command: 'focus-workspace-down' },
			// 		{ name: '▲', command: 'focus-workspace-up' },
			// 		{ name: 'Prev', command: 'focus-workspace-previous' },
    	// 		// FocusWorkspace {reference: WorkspaceReferenceArg,},
			// 	]
			// },
			// workspaceMove: {
			// 	label: 'Workspace\nmove',
			// 	items: [
			// 		{ name: '▼', command: 'move-workspace-down' },
			// 		{ name: '▲', command: 'move-workspace-up' },
			// 		{ name: 'To 🖥️ ◀', command: 'move-workspace-to-monitor-left' },
			// 		{ name: 'To 🖥️ ▶', command: 'move-workspace-to-monitor-right' },
			// 		{ name: 'To 🖥️ ▼', command: 'move-workspace-to-monitor-down' },
			// 		{ name: 'To 🖥️ ▲', command: 'move-workspace-to-monitor-up' },
			// 		{ name: 'To 🖥️ Prev', command: 'move-workspace-to-monitor-previous' },
			// 		{ name: 'To 🖥️ Next', command: 'move-workspace-to-monitor-next' },
			// 		// MoveWorkspaceToIndex {index: usize,reference: Option<WorkspaceReferenceArg>,},
			// 		// MoveWorkspaceToMonitor {output: String,reference: Option<WorkspaceReferenceArg>,},
			// 	]
			// },
			// column: {
			// 	label: 'Col',
			// 	items: [
			// 		{ name: 'ConsumeWindowIntoColumn', command: 'consume-window-into-column' },
			// 		{ name: 'ExpelWindowFromColumn', command: 'expel-window-from-column' },
			// 		{ name: 'SwapWindowRight', command: 'swap-window-right' },
			// 		{ name: 'SwapWindowLeft', command: 'swap-window-left' },
			// 		{ name: 'ToggleColumnTabbedDisplay', command: 'toggle-column-tabbed-display' },
			// 		{ name: 'CenterColumn', command: 'center-column' },
			// 		{ name: 'CenterVisibleColumns', command: 'center-visible-columns' },
			// 		{ name: 'SwitchPresetColumnWidth', command: 'switch-preset-column-width' },
			// 		{ name: 'SwitchPresetColumnWidthBack', command: 'switch-preset-column-width-back' },
			// 		{ name: 'MaximizeColumn', command: 'maximize-column' },
			// 		{ name: 'ExpandColumnToAvailableWidth', command: 'expand-column-to-available-width' },
			// 		// SetColumnDisplay {display: ColumnDisplay,},
			// 		// SetColumnWidth {change: SizeChange,},
			// 	]
			// },
			screenshot: {
				label: 'Screenshot',
				items: [
					{ name: 'Screenshot', command: 'screenshot' },// Screenshot {show_pointer: bool,},
					{ name: 'ScreenshotScreen', command: 'screenshot-screen -d false' },// ScreenshotScreen {write_to_disk: bool,show_pointer: bool,},
					{ name: 'ScreenshotWindow', command: 'screenshot-window -d false' },// ScreenshotWindow {id: Option<u64>,write_to_disk: bool,},
				]
			},
			// window: {
			// 	label: 'Window',
			// 	items: [
			// 		{ name: 'CloseWindow', command: 'close-window' },// CloseWindow {id: Option<u64>,},
    	// 		{ name: 'FullscreenWindow', command: 'fullscreen-window' },// FullscreenWindow {id: Option<u64>,},
    	// 		{ name: 'ToggleWindowedFullscreen', command: 'toggle-windowed-fullscreen' },// ToggleWindowedFullscreen {id: Option<u64>,},
			// 		{ name: 'SwapWindowRight', command: 'swap-window-right' },// SwapWindowRight {},
			// 		{ name: 'SwapWindowLeft', command: 'swap-window-left' },// SwapWindowLeft {},
			// 		{ name: 'CenterWindow', command: 'center-window' },// CenterWindow {id: Option<u64>,},
			// 		{ name: 'ResetWindowHeight', command: 'reset-window-height' },// ResetWindowHeight {id: Option<u64>,},
			// 		{ name: 'SwitchPresetWindowWidth', command: 'switch-preset-window-width' },// SwitchPresetWindowWidth {id: Option<u64>,},
			// 		{ name: 'SwitchPresetWindowWidthBack', command: 'switch-preset-window-width-back' },// SwitchPresetWindowWidthBack {id: Option<u64>,},
			// 		{ name: 'SwitchPresetWindowHeight', command: 'switch-preset-window-height' },// SwitchPresetWindowHeight {id: Option<u64>,},
			// 		{ name: 'SwitchPresetWindowHeightBack', command: 'switch-preset-window-height-back' },// SwitchPresetWindowHeightBack {id: Option<u64>,},
			// 		{ name: 'ToggleWindowFloating', command: 'toggle-window-floating' },// ToggleWindowFloating {id: Option<u64>,},
			// 		{ name: 'ToggleWindowRuleOpacity', command: 'toggle-window-rule-opacity' },// ToggleWindowRuleOpacity {id: Option<u64>,},
			// 		{ name: 'ToggleWindowUrgent', command: 'toggle-window-urgent' },// ToggleWindowUrgent {id: u64,},
			// 		{ name: 'SetWindowUrgent', command: 'set-window-urgent' },// SetWindowUrgent {id: u64,},
			// 		{ name: 'UnsetWindowUrgent', command: 'unset-window-urgent' },// UnsetWindowUrgent {id: u64,},
			// 		{ name: 'SetDynamicCastWindow', command: 'set-dynamic-cast-window' },// SetDynamicCastWindow {id: Option<u64>,},
			// 		{ name: 'MoveFloatingWindow', command: 'move-floating-window' },// MoveFloatingWindow {id: Option<u64>,x: PositionChange,y: PositionChange,},
			// 		{ name: 'SetWindowWidth', command: 'set-window-width' },// SetWindowWidth {id: Option<u64>,change: SizeChange,},
			// 		{ name: 'SetWindowHeight', command: 'set-window-height' },// SetWindowHeight {id: Option<u64>,change: SizeChange,},
			// 	]
			// },
		}
	})()